language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "0.12"
  - "0.10"
  - "iojs"

sudo: false

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

after_success:
  - make publish-coverage

matrix:
  fast_finish: true
