language: node_js
node_js:
  - "node"
  - "4"
  - "0.12"
  - "0.10"

sudo: false

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

after_success:
  - make publish-coverage

matrix:
  fast_finish: true
