language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: false

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

after_success:
  - make publish-coverage

matrix:
  fast_finish: true
